# Generated by Django 5.0.4 on 2024-05-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_message_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
    ]
